(function () {
  'use strict';
  var data=window.IVY_TYPE_CONTENT,asset='../../web/public/assets/',live='http://127.0.0.1:3010',c=data.campuses[0];
  function esc(value){return String(value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
  function picture(name,alt,extra){return '<img src="'+asset+esc(name)+'.webp" alt="'+esc(alt)+'" decoding="async" '+(extra||'loading="lazy"')+'>'}
  var about=data.home.about.bodyText;
  var sentences=about.match(/[^。！？]+[。！？]+/g)||[about];
  var excerpt=sentences.slice(0,3).join('');
  document.getElementById('app').innerHTML=
    '<header class="header"><a class="brand" href="'+live+'/" target="_blank" rel="noopener"><img src="../../web/public/favicon-48.png" width="48" height="48" alt=""><span><strong>常春藤教育機構</strong><small lang="en">Ivy Educational Institution</small></span></a><nav aria-label="區塊導覽"><a href="#about">關於常春藤</a><a href="#campuses">分校資訊</a><a href="#news">最新消息</a></nav><a class="header-book" href="'+live+'/visit" target="_blank" rel="noopener">預約參觀<small lang="en">Book a Visit</small></a></header>'+
    '<main><section class="hero wrap" id="hero"><div><span class="eyebrow hero-eyebrow">'+esc(data.home.hero.eyebrow)+'</span><h1 class="hero-title">在常春藤，<br>每一天都有<span>新發現</span>。</h1><p class="hero-copy">'+data.home.hero.copyLines.map(esc).join('<br>')+'</p><a class="button hero-button" href="'+live+'/#life" target="_blank" rel="noopener">看看孩子的一天</a></div><figure>'+picture(data.home.hero.heroImage,data.home.hero.heroImageAlt,'fetchpriority="high"')+'</figure></section>'+
    '<section class="about" id="about"><div class="wrap about-grid"><div><span class="eyebrow about-eyebrow" lang="en">SINCE 1997</span><h2 class="belief-title">把每個孩子，<br>放在心上。</h2><p class="belief-copy">'+esc(excerpt)+'</p><a class="text-link" href="#campuses">認識五所校園</a></div><figure class="about-photo">'+picture(data.home.about.photos[0].image,data.home.about.photos[0].alt)+'<figcaption>把日常，變成值得記住的童年。</figcaption></figure></div></section>'+
    '<section class="campus wrap" id="campuses"><div class="campus-heading"><h2>分校資訊</h2><span lang="en">Campuses</span></div><nav class="campus-tabs" aria-label="五校導覽">'+data.campuses.map(function(s){return '<a href="'+live+'/campuses/'+s.key+'" target="_blank" rel="noopener"'+(s.key===c.key?' class="is-selected"':'')+'>'+picture('campus-line-art-'+s.key,'')+'<span>'+esc(s.name)+'</span></a>'}).join('')+'</nav><figure class="campus-photo">'+picture(c.image,c.name+'校園外觀')+'</figure><div class="campus-info"><div><span class="district">高雄 · '+esc(c.district)+'</span><h3>'+esc(c.name)+'</h3><span class="campus-en" lang="en">'+c.key.toUpperCase()+' CAMPUS</span></div><div class="campus-contact"><a class="address" href="https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(c.address)+'" target="_blank" rel="noopener">'+esc(c.address)+'</a><a class="phone" lang="en" href="tel:'+esc(c.phone)+'">'+esc(c.phone)+'</a><a class="social" href="'+esc(c.line)+'" target="_blank" rel="noopener">LINE 好友 ↗</a></div><a class="button campus-button" href="'+live+'/visit/'+c.key+'" target="_blank" rel="noopener">預約參觀'+esc(c.name)+'</a></div></section>'+
    '<section class="news" id="news"><div class="wrap news-layout"><div class="events"><div class="news-heading"><span class="kicker" lang="en">UPCOMING EVENTS</span><h2 class="info-heading">近期活動</h2></div><div class="event-list">'+data.news.events.map(function(ev,i){return '<button class="event" data-detail="event-'+i+'"><span class="date"><b>'+esc(ev.date.slice(-2))+'</b><span lang="en">'+esc(ev.month)+'</span></span><span class="event-copy"><small>'+esc(ev.campus)+'</small><strong>'+esc(ev.title)+'</strong></span></button>'}).join('')+'</div><button class="more" data-list="events">所有活動</button></div><div class="articles"><div class="news-heading news-heading-row"><div><span class="kicker" lang="en">LATEST NEWS</span><h2 class="info-heading">最新消息</h2></div><button class="more" data-list="articles">所有最新消息</button></div><div class="news-cards">'+data.news.articles.slice(0,3).map(function(a,i){return '<article class="news-card">'+picture(a.image,a.alt)+'<div class="meta"><span>'+esc(a.campus)+'</span><time>'+esc(a.date.replaceAll('-','.'))+'</time></div><h3><button data-detail="article-'+i+'">'+esc(a.title)+'</button></h3><p>'+esc(a.description)+'</p></article>'}).join('')+'</div></div></div><p class="wrap sample-note">'+esc(data.news.sampleNote)+'</p></section></main>'+
    '<footer class="wrap"><a class="footer-name" href="'+live+'/" target="_blank" rel="noopener">常春藤教育機構</a><p>陪伴每一個孩子，長成自己喜歡的樣子。</p><span>參觀時間與入學資訊，請向各校確認。</span></footer>'+
    '<dialog class="detail-dialog" aria-labelledby="detail-title"><div class="dialog-top"><span>常春藤 · 校園消息</span><button class="close-dialog" aria-label="關閉消息">關閉</button></div><div id="detail-body"></div><p class="dialog-note">'+esc(data.news.sampleNote)+'</p></dialog>';

  var dialog=document.querySelector('dialog'),opener=null;
  function showDetail(kind,index){var item=kind==='event'?data.news.events[index]:data.news.articles[index];document.getElementById('detail-body').innerHTML='<span class="detail-date">'+esc(item.date)+' · '+esc(item.campus)+'</span><h2 id="detail-title">'+esc(item.title)+'</h2>'+(item.image?picture(item.image,item.alt):'')+'<p>'+esc(item.description)+'</p>';if(!dialog.open)dialog.showModal()}
  document.querySelectorAll('[data-detail]').forEach(function(b){b.addEventListener('click',function(){opener=b;var bits=b.dataset.detail.split('-');showDetail(bits[0],Number(bits[1]))})});
  document.querySelectorAll('[data-list]').forEach(function(b){b.addEventListener('click',function(){opener=b;var events=b.dataset.list==='events',items=events?data.news.events:data.news.articles;document.getElementById('detail-body').innerHTML='<h2 id="detail-title">'+(events?'近期活動':'最新消息')+'</h2><div class="dialog-list">'+items.map(function(a,i){return '<button data-item="'+i+'"><time>'+esc(a.date)+'</time><strong>'+esc(a.title)+'</strong></button>'}).join('')+'</div>';dialog.showModal();dialog.querySelectorAll('[data-item]').forEach(function(item){item.addEventListener('click',function(){showDetail(events?'event':'article',Number(item.dataset.item))})})})});
  document.querySelector('.close-dialog').addEventListener('click',function(){dialog.close()});dialog.addEventListener('close',function(){if(opener)opener.focus({preventScroll:true})});dialog.addEventListener('click',function(ev){if(ev.target===dialog){var rect=dialog.getBoundingClientRect();if(ev.clientX<rect.left||ev.clientX>rect.right||ev.clientY<rect.top||ev.clientY>rect.bottom)dialog.close()}});
  function jump(section){var target=document.getElementById(section);if(target)target.scrollIntoView({block:'start',behavior:'instant'})}
  function setVariant(variant){if(!['current','proposal'].includes(variant))return;var sections=[...document.querySelectorAll('main>section')];var current=sections.find(function(s){return s.getBoundingClientRect().bottom>80})||sections[0];var before=current.getBoundingClientRect().top;document.documentElement.dataset.variant=variant;var next=new URL(location.href);next.searchParams.set('variant',variant);history.replaceState(null,'',next);requestAnimationFrame(function(){window.scrollBy({top:current.getBoundingClientRect().top-before,behavior:'instant'})})}
  window.addEventListener('message',function(event){if(event.origin!==location.origin||event.source!==parent||!event.data)return;if(event.data.type==='ivy-type-variant')setVariant(event.data.variant);if(event.data.type==='ivy-type-section')jump(event.data.section)});
  document.fonts.ready.then(function(){var hash=location.hash.slice(1);if(hash)jump(hash);parent.postMessage({type:'ivy-type-ready'},location.origin)});
})();
