"""Bundle the local prototype into a self-contained HTML, without dependencies."""
from pathlib import Path
import base64

root = Path(__file__).resolve().parent
# Inline the small wordmark subsets so index.html also works when opened as a file.
brand_font_rules = []
for family, weight, filename in (
    ('Noto Sans TC', 600, 'noto-sans-tc-600-brand.woff'),
    ('Source Sans 3', 400, 'source-sans-3-400-brand.woff'),
):
    encoded = base64.b64encode((root / 'assets' / 'fonts' / filename).read_bytes()).decode()
    brand_font_rules.append(
        "@font-face{font-family:'" + family + "';font-style:normal;font-weight:" + str(weight)
        + ";font-display:swap;src:url(data:font/woff;base64," + encoded + ") format('woff')}"
    )
brand_css = '/* Generated by package_preview.py; sources and licenses: README.md. */\n' + '\n'.join(brand_font_rules) + '\n'
(root / 'assets' / 'fonts' / 'brand-fonts.css').write_text(brand_css)
html = (root / 'index.html').read_text()
css = (root / 'styles.css').read_text() + '\n' + (root / 'studio.css').read_text()
js = (root / 'app.js').read_text()
assets = {}
for path in sorted((root / 'assets').glob('*')):
    if path.suffix not in ('.webp', '.png'):
        continue
    mime = 'image/png' if path.suffix == '.png' else 'image/webp'
    assets[path.name] = 'data:' + mime + ';base64,' + base64.b64encode(path.read_bytes()).decode()
import json
js = 'const EMBEDDED_ASSETS = ' + json.dumps(assets) + ';\n' + js.replace("'use strict';", '')
photo_src = "const photoSrc = name=>'assets/'+name+'.webp';"
assert photo_src in js, 'app.js 的 photoSrc 定義變了，打包器要同步改'
js = js.replace(photo_src, "const photoSrc = name=>EMBEDDED_ASSETS[name+'.webp'];")
js = js.replace("'assets/'+trigger.dataset.photo+'.webp'", "EMBEDDED_ASSETS[trigger.dataset.photo+'.webp']")
js = js.replace('poster="assets/hero-campus-still.webp"', 'poster="${EMBEDDED_ASSETS[\'hero-campus-still.webp\']}"')
video = root / 'assets' / 'hero-campus.mp4'
if video.exists():
    js = js.replace("const HERO_VIDEO_SRC = 'assets/hero-campus.mp4';", "const HERO_VIDEO_SRC = 'data:video/mp4;base64," + base64.b64encode(video.read_bytes()).decode() + "';")
import re
html = re.sub(r'<link rel="preload"[^>]*href="assets/[^"]+"[^>]*>', '', html)
for font in sorted((root / 'assets' / 'fonts').glob('*.woff')):
    css = css.replace('url(assets/fonts/' + font.name + ')', 'url(data:font/woff;base64,' + base64.b64encode(font.read_bytes()).decode() + ')')
html = html.replace('src="assets/logo.png"', 'src="' + assets['logo.png'] + '"')
html = html.replace('href="assets/logo.png"', 'href="' + assets['logo.png'] + '"')
css = css.replace('url("assets/logo.png")', 'url("' + assets['logo.png'] + '")')
html = html.replace('<link rel="stylesheet" href="styles.css">', '<style>' + css + '</style>')
html = html.replace('<link rel="stylesheet" href="studio.css">', '')
html = html.replace('<link rel="stylesheet" href="assets/fonts/brand-fonts.css">', '<style>' + brand_css + '</style>')
html = html.replace('<script src="app.js" defer></script>', '')
html = html.replace('</body>', '<script>\n' + js + '\n</script></body>')
(root / 'preview.html').write_text(html)
print('Created preview.html:', len(html.encode()), 'bytes')
