import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

type ScrollIdle = typeof import('../app/utils/scrollIdle')
let scheduleScrollIdle: ScrollIdle['scheduleScrollIdle']
let isScrollIdle: ScrollIdle['isScrollIdle']
let browser: EventTarget

function deferred() {
  let resolve!: () => void
  const promise = new Promise<void>((done) => { resolve = done })
  return { promise, resolve }
}

describe('手機紙張的共用 scroll-idle 佇列', () => {
  beforeEach(async () => {
    vi.resetModules()
    vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout', 'performance'] })
    browser = new EventTarget()
    vi.stubGlobal('window', browser)
    ;({ scheduleScrollIdle, isScrollIdle } = await import('../app/utils/scrollIdle'))
  })
  afterEach(() => {
    vi.clearAllTimers()
    vi.useRealTimers()
    vi.unstubAllGlobals()
    vi.restoreAllMocks()
  })

  it('先觀測 200ms 才初始化，結束後釋放 timer 與 scroll listener', async () => {
    const add = vi.spyOn(browser, 'addEventListener')
    const remove = vi.spyOn(browser, 'removeEventListener')
    const task = vi.fn(() => { expect(isScrollIdle()).toBe(true) })
    expect(isScrollIdle()).toBe(false)
    scheduleScrollIdle(task)
    expect(isScrollIdle()).toBe(false)
    await vi.advanceTimersByTimeAsync(199)
    expect(task).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(task).toHaveBeenCalledTimes(1)
    expect(add).toHaveBeenCalledTimes(1)
    expect(add).toHaveBeenCalledWith('scroll', expect.any(Function), { passive: true })
    expect(remove).toHaveBeenCalledWith('scroll', add.mock.calls[0]![1])
    expect(vi.getTimerCount()).toBe(0)
    expect(isScrollIdle()).toBe(false)
  })

  it('慣性捲動期間持續延後，從最後一個 scroll 起重新等待', async () => {
    const task = vi.fn()
    scheduleScrollIdle(task)
    await vi.advanceTimersByTimeAsync(150)
    browser.dispatchEvent(new Event('scroll'))
    await vi.advanceTimersByTimeAsync(150)
    browser.dispatchEvent(new Event('scroll'))
    await vi.advanceTimersByTimeAsync(199)
    expect(task).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(task).toHaveBeenCalledTimes(1)
  })

  it('async 初始化不重疊，完成後再留 200ms 才開始下一張', async () => {
    const add = vi.spyOn(browser, 'addEventListener')
    const remove = vi.spyOn(browser, 'removeEventListener')
    const work = deferred()
    const first = vi.fn(() => work.promise)
    const second = vi.fn()
    scheduleScrollIdle(first)
    scheduleScrollIdle(second)
    await vi.advanceTimersByTimeAsync(200)
    expect(first).toHaveBeenCalledTimes(1)
    await vi.advanceTimersByTimeAsync(1000)
    expect(second).not.toHaveBeenCalled()
    expect(remove).not.toHaveBeenCalled()
    work.resolve()
    await vi.advanceTimersByTimeAsync(199)
    expect(second).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(second).toHaveBeenCalledTimes(1)
    expect(add).toHaveBeenCalledTimes(1)
    expect(remove).toHaveBeenCalledTimes(1)
    expect(vi.getTimerCount()).toBe(0)
  })

  it('task 等待 module/fonts 時仍能偵測捲動恢復', async () => {
    const work = deferred()
    scheduleScrollIdle(() => work.promise)
    await vi.advanceTimersByTimeAsync(200)
    expect(isScrollIdle()).toBe(true)
    browser.dispatchEvent(new Event('scroll'))
    expect(isScrollIdle()).toBe(false)
    await vi.advanceTimersByTimeAsync(199)
    expect(isScrollIdle()).toBe(false)
    await vi.advanceTimersByTimeAsync(1)
    expect(isScrollIdle()).toBe(true)
    work.resolve()
    await vi.advanceTimersByTimeAsync(0)
    expect(isScrollIdle()).toBe(false)
    expect(vi.getTimerCount()).toBe(0)
  })

  it('取消中間卡片保留其他卡片順序，不重複建立 listener', async () => {
    const add = vi.spyOn(browser, 'addEventListener')
    const order: string[] = []
    scheduleScrollIdle(() => { order.push('first') })
    const cancelled = vi.fn()
    const cancel = scheduleScrollIdle(cancelled)
    scheduleScrollIdle(() => { order.push('last') })
    cancel()
    cancel()
    await vi.advanceTimersByTimeAsync(200)
    expect(order).toEqual(['first'])
    await vi.advanceTimersByTimeAsync(200)
    expect(order).toEqual(['first', 'last'])
    expect(cancelled).not.toHaveBeenCalled()
    expect(add).toHaveBeenCalledTimes(1)
    expect(vi.getTimerCount()).toBe(0)
  })

  it('離頁取消所有待辦即清理資源，返回後重新等待完整 idle', async () => {
    const add = vi.spyOn(browser, 'addEventListener')
    const remove = vi.spyOn(browser, 'removeEventListener')
    const cancelled = vi.fn()
    const cancel = scheduleScrollIdle(cancelled)
    await vi.advanceTimersByTimeAsync(150)
    cancel()
    expect(remove).toHaveBeenCalledTimes(1)
    expect(vi.getTimerCount()).toBe(0)
    await vi.advanceTimersByTimeAsync(1000)
    expect(cancelled).not.toHaveBeenCalled()
    const next = vi.fn()
    scheduleScrollIdle(next)
    await vi.advanceTimersByTimeAsync(199)
    expect(next).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(next).toHaveBeenCalledTimes(1)
    expect(add).toHaveBeenCalledTimes(2)
    expect(remove).toHaveBeenCalledTimes(2)
  })

  it('取消已開始的 task 不強制中止它，await 期間持續觀測', async () => {
    const remove = vi.spyOn(browser, 'removeEventListener')
    const work = deferred()
    const cancel = scheduleScrollIdle(() => work.promise)
    await vi.advanceTimersByTimeAsync(200)
    cancel()
    expect(remove).not.toHaveBeenCalled()
    browser.dispatchEvent(new Event('scroll'))
    expect(isScrollIdle()).toBe(false)
    work.resolve()
    await vi.advanceTimersByTimeAsync(0)
    expect(remove).toHaveBeenCalledTimes(1)
    expect(vi.getTimerCount()).toBe(0)
  })

  it('task reject 後回報錯誤，仍以間隔執行後續 task', async () => {
    const error = new Error('init failed')
    const log = vi.spyOn(console, 'error').mockImplementation(() => {})
    const next = vi.fn()
    scheduleScrollIdle(async () => { throw error })
    scheduleScrollIdle(next)
    await vi.advanceTimersByTimeAsync(200)
    expect(log).toHaveBeenCalledWith('[scrollIdle] Task failed', error)
    expect(next).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(200)
    expect(next).toHaveBeenCalledTimes(1)
    expect(vi.getTimerCount()).toBe(0)
  })

  it('執行中可自行重新排隊，重試不會立刻遞迴初始化', async () => {
    const retry = vi.fn()
    scheduleScrollIdle(() => { scheduleScrollIdle(retry) })
    await vi.advanceTimersByTimeAsync(200)
    expect(retry).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(199)
    expect(retry).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(1)
    expect(retry).toHaveBeenCalledTimes(1)
    expect(vi.getTimerCount()).toBe(0)
  })
})
