from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb68559bda1a'
down_revision: Union[str, None] = '7ed117ce6188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_slots_campus_key'), 'visit_slots', ['campus_key'], unique=False)
    op.create_table('visit_contact_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visit_request_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_request_id'], ['visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_contact_notes_visit_request_id'), 'visit_contact_notes', ['visit_request_id'], unique=False)
    op.add_column('visit_requests', sa.Column('slot_id', sa.Uuid(), nullable=True))
    op.add_column('visit_requests', sa.Column('assigned_staff_id', sa.Uuid(), nullable=True))
    op.add_column('visit_requests', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('visit_requests', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('visit_requests', sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_visit_requests_slot_id'), 'visit_requests', ['slot_id'], unique=False)
    op.create_foreign_key(None, 'visit_requests', 'visit_slots', ['slot_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'visit_requests', 'users', ['assigned_staff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_requests', type_='foreignkey')
    op.drop_constraint(None, 'visit_requests', type_='foreignkey')
    op.drop_index(op.f('ix_visit_requests_slot_id'), table_name='visit_requests')
    op.drop_column('visit_requests', 'follow_up_at')
    op.drop_column('visit_requests', 'cancelled_at')
    op.drop_column('visit_requests', 'confirmed_at')
    op.drop_column('visit_requests', 'assigned_staff_id')
    op.drop_column('visit_requests', 'slot_id')
    op.drop_index(op.f('ix_visit_contact_notes_visit_request_id'), table_name='visit_contact_notes')
    op.drop_table('visit_contact_notes')
    op.drop_index(op.f('ix_visit_slots_campus_key'), table_name='visit_slots')
    op.drop_table('visit_slots')
    # ### end Alembic commands ###
