"""從現有 Bold 子集切出首屏字形，保留其餘全部字形與原始字寬。

執行：python3 scripts/subset-critical-fonts.py（需 fontTools、Brotli）
首屏文案改動可重跑；未列入首屏的字仍由 remaining 字型提供。
"""
from pathlib import Path
from hashlib import sha256
from io import BytesIO
import json
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'web/public/assets/fonts/lineseed-bd.woff'
OUTPUT = ROOT / 'web/public/assets/fonts/subsets'
OUTPUT.mkdir(exist_ok=True)
site = json.loads((ROOT / 'web/server/data/site-fixture.json').read_text())
text = ''.join(site['home']['hero']['titleParts'].values()) + ''.join(c['name'] for c in site['campuses'])
original = TTFont(SOURCE, recalcTimestamp=False)
cmap = original.getBestCmap()
critical = {ord(char) for char in text} & cmap.keys()
groups = {'critical': critical, 'remaining': cmap.keys() - critical}
manifest = {}
rules = []
coverage = set()
for name, codepoints in groups.items():
    font = TTFont(SOURCE, recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = ['*']
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=codepoints)
    sub.subset(font)
    font.flavor = 'woff2'
    buffer = BytesIO()
    font.save(buffer)
    data = buffer.getvalue()
    check = TTFont(BytesIO(data))
    actual = check.getBestCmap()
    assert set(actual) == set(codepoints), f'{name}: 字形覆蓋改變'
    for cp, glyph in actual.items():
        assert check['hmtx'][glyph] == original['hmtx'][cmap[cp]], f'U+{cp:04X}: 字寬改變'
    coverage.update(actual)
    filename = f'lineseed-bd-{name}-{sha256(data).hexdigest()[:12]}.woff2'
    target = OUTPUT / filename
    if not target.exists() or target.read_bytes() != data:
        target.write_bytes(data)
    url = f'/assets/fonts/subsets/{filename}'
    ranges = ','.join(f'U+{cp:X}' for cp in sorted(codepoints))
    rules.append(f"@font-face{{font-family:'LINE Seed TW';font-weight:700;font-display:swap;src:url({url}) format('woff2'),url(/assets/fonts/lineseed-bd.woff) format('woff');unicode-range:{ranges}}}")
    manifest[name] = {'src': url, 'bytes': len(data), 'characters': len(actual)}
assert coverage == set(cmap), '切片聯集與原字型不一致'
(ROOT / 'web/app/assets/css/font-subsets.css').write_text('/* Generated by scripts/subset-critical-fonts.py; preserve all original glyphs. */\n' + '\n'.join(rules) + '\n')
(ROOT / 'web/app/generated/font-manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(json.dumps(manifest, indent=2))
