'use strict';
if ('scrollRestoration' in history) history.scrollRestoration = 'manual';
// Add a locally hosted MP4 here when the school video is ready.
// Empty source intentionally shows the campus cover without a fake play button.
const HERO_VIDEO_SRC = '';
const campuses = {
 yihua:{name:'義華校',district:'三民區',address:'高雄市三民區義華路68號',phone:'07-392-8366',image:'campus',intro:'在義華路上，走進孩子的日常。',description:'從戶外廣場、綠色園藝到共創教室，認識孩子每天活動、探索與學習的空間。義華校重視愛與關懷、閱讀素養與生活自理，陪伴孩子練習與世界相處。'},
 minghua:{name:'明華校',district:'左營區',address:'高雄市左營區明華一路176號',phone:'07-556-6796',image:'minghua',intro:'在明華一路，認識我們的校園。',description:'明華校位於高雄市左營區明華一路。先從校園外觀與所在位置認識學校，再安排一次參觀，親自了解孩子的學習環境與接送動線。'},
 chongde:{name:'崇德校',district:'左營區',address:'高雄市左營區崇德路87號',phone:'07-341-6286',image:'chongde',intro:'從崇德路，開始一段校園探索。',description:'崇德校位於高雄市左營區崇德路。歡迎預約到園，看看校園空間，也與園所聊聊孩子的需要、生活安排與入學準備。'},
 international:{name:'國際校',district:'鳥松區',address:'高雄市鳥松區球場路59號',phone:'07-370-8001',image:'international',intro:'走進鳥松，認識國際校。',description:'國際校位於高雄市鳥松區球場路。透過實際走訪了解校園環境與接送路線，並向園所確認適合孩子的課程與入學安排。'},
 renwu:{name:'仁武校',district:'仁武區',address:'高雄市仁武區京吉一路102號',phone:'07-375-7081',image:'renwu',intro:'在仁武，遇見下一段成長。',description:'仁武校位於高雄市仁武區京吉一路。歡迎帶著對孩子成長的期待來認識校園，參觀時也可以與園所討論課程、生活照顧與接送安排。'}
};
const main = document.querySelector('#main');
const nav = document.querySelector('#navigation');
const menu = document.querySelector('#menu-toggle');
const esc = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img = (name,alt,cls='',eager=false,priority=false)=>`<img class="${cls}" src="assets/${name}.webp" alt="${esc(alt)}" loading="${eager?'eager':'lazy'}"${priority?' fetchpriority="high"':''} decoding="async">`;
const mapURL = c=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(c.address);
const bookingLink = key=>'#/visit'+(key?'/'+key:'');
const icon = name=>`<svg class="icon" aria-hidden="true" focusable="false"><use href="#i-${name}"/></svg>`;
const arrow = icon('arrow-up-right');
const external = 'target="_blank" rel="noopener noreferrer"';
let currentPage='';
let lastPhotoTrigger=null;
let routeVersion=0;
let disposeMedia=()=>{};
function banner(key='') {return `<section class="visit-banner"><div class="container"><div><span class="eyebrow">預約參觀</span><h2 class="section-title">親自走一趟，感受${key?campuses[key].name:'常春藤'}的日常。</h2><p>帶著孩子，也帶著你想了解的事。我們期待與你相遇。</p></div><a class="button yellow" href="${bookingLink(key)}">預約校園參觀</a></div></section>`;}
function faq(key='') {return `<div class="faq-list"><details><summary>第一次參觀，要怎麼預約？</summary><p>先選擇想參觀的校區，再留下家長稱呼、電話與方便聯絡的時段。這份 prototype 僅示範流程，不會送出資料；實際參觀請直接致電園所。</p></details><details><summary>參觀時可以了解哪些事情？</summary><p>可以詢問校園環境、課程與生活安排、接送方式，以及孩子入學前需要準備的事。各校參觀範圍與接待時間請先向園所確認。</p></details><details><summary>可以查詢招生年齡、名額與費用嗎？</summary><p>招生年齡、名額與費用依校區與學年度而異。請向${key?campuses[key].name:'欲參觀的園所'}確認；這份提案不提供即時招生名額或費用報價。</p></details><details><summary>五所校區的環境與課程都一樣嗎？</summary><p>各校空間與課程安排可能不同。你可以先比較所在地與接送距離，再於參觀時了解該校的實際內容。</p></details></div>`;}
const dayMoments = [
 {key:'hello',icon:'sun-horizon',label:'早安入園',period:'一天的開始',title:'早安，今天的我\n準備好了。',story:'和家人說聲再見，走進熟悉的校園。從整理小書包開始，一點一點，找到自己的步調。',image:'campus',caption:'義華校校園照片 · 入園情境示意',question:'孩子第一次上學，如何陪伴適應？',answer:'參觀時可以與園所聊聊：初次入園的陪伴方式、家長如何與老師聯繫，以及可以事先做哪些準備。',word:'一聲早安，是一天的小小起點。'},
 {key:'discover',icon:'magnifying-glass',label:'好奇探索',period:'上午的發現',title:'我的「為什麼」，\n今天又多了一個。',story:'摸一摸、看一看，再和同伴試一次。那些讓眼睛發亮的小發現，是認識世界的開始。',image:'learning',caption:'義華校學習情境照片',question:'孩子平常會接觸哪些學習活動？',answer:'可以詢問該校如何安排探索活動、使用哪些教具與素材，以及如何依照年齡和孩子的興趣調整內容。',word:'把好奇留住，把答案慢慢找出來。'},
 {key:'lunch',icon:'bowl-food',label:'一起用餐',period:'午間的小事',title:'「我自己來！」\n是今天的小進步。',story:'洗洗手、準備用餐，也練習照顧自己。每天重複的小事情，都可以成為成長的練習。',image:'classroom',caption:'義華校教室空間參考 · 用餐照片待補',question:'餐點、飲食需求與自理練習怎麼安排？',answer:'參觀時可詢問餐點安排、食物過敏或特殊飲食需求的溝通方式，以及老師如何協助孩子練習用餐。',word:'成長，也藏在生活的小事情裡。'},
 {key:'rest',icon:'moon-stars',label:'安靜片刻',period:'慢下來的午後',title:'小小的世界，\n也需要休息一下。',story:'把熱鬧的節奏放慢，留一點安靜給自己。休息之後，再帶著精神迎接下午。',image:'classroom',caption:'義華校教室空間參考 · 午休照片待補',question:'孩子睡不著，或有不同的休息需求呢？',answer:'可以向園所了解休息空間與安排，以及孩子尚未習慣午休時，老師會如何陪伴和與家長溝通。',word:'慢一點，也是在好好長大。'},
 {key:'outside',icon:'tree',label:'午後玩耍',period:'午後的冒險',title:'和朋友一起，\n把今天玩得好大。',story:'看看植物、動動身體，發現身邊的新鮮事。和同伴一起玩的時候，也在練習分享與表達。',image:'garden',caption:'義華校綠色園藝照片 · 戶外情境參考',question:'戶外活動與天氣變化如何安排？',answer:'參觀時可詢問戶外活動的空間、陪伴方式，以及下雨或天氣炎熱時，園所如何調整當天的安排。',word:'一小片自然，也能裝下很多發現。'},
 {key:'home',icon:'house-line',label:'帶故事回家',period:'把今天帶回家',title:'今天的好多事，\n想第一個告訴你。',story:'帶上書包，也帶上今天的新發現。和家人分享一件開心的小事，讓校園裡的故事繼續走進生活。',image:'hero',caption:'義華校生活照片 · 離園情境示意',question:'接送與家長聯繫，有哪些需要先知道？',answer:'可以詢問園所的接送流程、家長與老師的聯繫方式，以及如何了解孩子在校的生活情況。',word:'把新發現，帶回最熟悉的懷抱。'}
];
function dayExperience(){return `<section class="section day-experience" id="life" aria-labelledby="day-heading"><div class="container"><div class="day-heading"><div><span class="eyebrow">孩子的一天</span><h2 class="section-title" id="day-heading">跟著孩子，過一天。</h2></div><p>點選一個片刻，<br>看看成長如何在日常裡發生。</p></div><div class="day-trail" role="tablist" aria-label="孩子的一天，選擇生活片刻">${dayMoments.map((m,i)=>`<button type="button" class="day-tab" role="tab" id="day-tab-${m.key}" aria-controls="day-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-moment="${i}"><span class="day-dot" aria-hidden="true">${icon(m.icon)}</span><span>${m.label}</span></button>`).join('')}</div><p class="sr-only" id="day-status" aria-live="polite"></p><div id="day-panel" class="day-panel" role="tabpanel" aria-labelledby="day-tab-hello" tabindex="0"></div><div class="day-bottom"><p>日常情境提案，以義華校影像呈現；各校、各班實際作息請向園所確認。</p><a class="text-link" href="#/home/campuses">想親自看看？認識五所校園</a></div></div></section>`;}
function setupDayExperience(){
 const panel=document.querySelector('#day-panel');if(!panel)return;
 const tabs=[...document.querySelectorAll('.day-tab')];let current=0,ready=false;const visited=new Set();
 function show(index,focusTab=false){
  current=index;visited.add(index);const m=dayMoments[index];
  tabs.forEach((tab,i)=>{const active=i===index;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;tab.classList.toggle('visited',visited.has(i));});
  panel.setAttribute('aria-labelledby',`day-tab-${m.key}`);panel.dataset.moment=m.key;
  panel.innerHTML=`<figure class="day-scene">${img(m.image,m.caption,'day-photo',true)}<div class="day-photo-shade"></div><div class="day-photo-copy"><span>今天的小小記憶</span><p>${m.word}</p></div><figcaption>${m.caption}</figcaption></figure><div class="day-story"><div class="day-chapter"><span>${m.period}</span><span class="day-counter">${String(index+1).padStart(2,'0')} <span>/ 06</span></span></div><h3>${m.title.split('\n').join('<br>')}</h3><p class="day-narrative">${m.story}</p><details class="day-parent"><summary><span class="day-parent-label">給正在了解學校的你</span><span class="day-question">${m.question}<span aria-hidden="true">＋</span></span></summary><p>${m.answer}</p></details><div class="day-controls"><span class="day-visited">已探索 ${visited.size} / 6 個片刻</span><div><button type="button" data-day-prev ${index===0?'disabled':''} aria-label="上一個生活片刻">${icon('arrow-left')}</button><button type="button" data-day-next>${index===5?'再看一次'+icon('arrow-counter-clockwise'):'下一個片刻'+icon('arrow-right')}</button></div></div></div>`;
  if(focusTab){tabs[index].focus({preventScroll:true});}
  if(ready)document.querySelector('#day-status').textContent=`第 ${index+1} 個片刻：${m.label}。已探索 ${visited.size} / 6 個片刻。`;
 }
 tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>show(i));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();show(next,true);}});});
 panel.addEventListener('click',e=>{const next=e.target.closest('[data-day-next]'),previous=e.target.closest('[data-day-prev]');if(!next&&!previous)return;show(next?(current+1)%dayMoments.length:Math.max(0,current-1));if(matchMedia('(max-width: 760px)').matches){panel.focus({preventScroll:true});panel.scrollIntoView({block:'start',behavior:'instant'});}else{const control=panel.querySelector(next?'[data-day-next]':'[data-day-prev]');if(!control.disabled)control.focus({preventScroll:true});else tabs[current].focus({preventScroll:true});}});
 show(0);ready=true;
}

function home(){return `
<section class="hero" aria-labelledby="home-title">
 ${img('hero','義華校的戶外活動與孩子的校園生活','hero-photo',true,true)}
 <video id="hero-video" class="hero-video" muted loop playsinline preload="none" poster="assets/hero.webp" aria-label="常春藤校園影片" hidden></video><div class="hero-shade"></div>
 <div class="container"><span class="eyebrow">常春藤幼兒園 · 高雄五校</span><h1 id="home-title">讓每一份好奇，<br><span>慢慢長大。</span></h1><p>在被理解、被陪伴的日常裡，<br>發現世界，也發現自己的可能。</p><div class="hero-cta"><a class="button yellow" href="#/home/campuses">走進五所校園</a><a class="text-link" href="#/home/about">認識常春藤</a></div></div>
 <div class="hero-bottom"><span class="hero-caption" id="media-caption">義華校生活影像 · 影片封面示意</span><div class="video-controls" id="video-controls" hidden><button id="video-play" type="button">${icon('play')}播放影片</button><button id="video-sound" type="button" aria-pressed="false">${icon('speaker-high')}開啟聲音</button></div><span class="scroll-hint">往下探索${icon('arrow-down')}</span></div>
</section>
<div class="welcome-strip"><div class="container"><p><strong>五所校園，同一份陪伴孩子的心。</strong> 從你熟悉的生活圈，找到常春藤。</p><a class="text-link" href="#/home/campuses">尋找校區</a></div></div>
<section class="section" id="about"><div class="container about-grid"><div><span class="eyebrow">認識常春藤</span><h2 class="section-title">成長的每一小步，<br>都值得好好陪伴。</h2><p class="section-copy">一個問題、一段故事、一次勇敢的嘗試。<br>我們相信，學習發生在孩子每天的生活裡。</p><p class="section-copy">從義華校的教育理念出發，認識常春藤重視的愛與關懷，以及閱讀、探索和生活自理的練習。也歡迎走進各校，找到適合孩子的成長環境。</p><a class="text-link" href="#/home/learning">我們重視的事</a></div><div class="about-photo">${img('campus','義華校校舍與戶外廣場')}<span class="photo-label">義華校 · 孩子每天生活的地方</span></div></div></section>
<section class="section campuses" id="campuses"><div class="container"><div class="section-heading"><div><span class="eyebrow">五校介紹</span><h2 class="section-title">五所校園，等你來認識。</h2></div><p>從生活圈與接送路線出發，<br>找到適合你與孩子的常春藤。</p></div><div class="campus-grid">${Object.entries(campuses).map(([key,c])=>`<article class="campus-card"><a class="campus-picture" href="#/${key}" aria-label="認識${c.name}">${img(c.image,c.name+'官方校園照片')}<span class="campus-region">高雄 · ${c.district}</span></a><div class="campus-topline"><h3><a href="#/${key}">${c.name}</a></h3></div><p class="campus-address">${c.address}</p><div class="campus-meta"><a href="tel:${c.phone}">${icon('phone')}${c.phone}</a><a href="#/${key}">認識校區</a></div></article>`).join('')}</div></div></section>
<section class="section" id="learning"><div class="container learning-grid"><div>${img('learning','義華校官網的學習情境','learning-photo')}<p class="learning-credit">照片與理念參考義華校官網；各校安排請向園所確認。</p></div><div><span class="eyebrow">教育理念</span><h2 class="section-title">從生活裡學習，<br>把成長帶向世界。</h2><p class="section-copy">尊重每個孩子不同的步調，<br>讓學習在理解與鼓勵中，自然發生。</p><div class="values"><div class="value"><span>01</span><h3>閱讀</h3><p>從一個故事開始，<br>遇見更大的世界。</p></div><div class="value"><span>02</span><h3>探索</h3><p>保留好奇，練習觀察，<br>在嘗試中找到答案。</p></div><div class="value"><span>03</span><h3>關懷</h3><p>學習表達與聆聽，<br>也學習與同伴相處。</p></div><div class="value"><span>04</span><h3>自理</h3><p>從每天的小事，<br>累積「我可以」的自信。</p></div></div></div></div></section>
${dayExperience()}
${campusTour('yihua',true)}
<section class="section news" id="news"><div class="container"><div class="section-heading"><div><span class="eyebrow">校園活動</span><h2 class="section-title">在常春藤，日子閃閃發亮。</h2></div><a class="text-link" href="https://www.ivykids.tw/our_activities.php" ${external}>更多義華校活動 ${arrow}</a></div><div class="news-grid"><article class="news-item">${img('water','義華校夏日玩水活動')}<small>義華校 / 校園生活</small><h3>把廣場變成夏天，<br>把歡笑留在童年。</h3><a class="text-link" href="https://www.ivykids.tw/our_activities_detail.php?id=56" ${external}>到原官網看活動 ${arrow}</a></article><article class="news-item">${img('graduation','義華校畢業典禮暨遊藝節目')}<small>義華校 / 成長紀錄</small><h3>站上舞台的那一刻，<br>看見孩子長大的模樣。</h3><a class="text-link" href="https://www.ivykids.tw/our_activities_detail.php?id=55" ${external}>到原官網看活動 ${arrow}</a></article></div></div></section>
<section class="section" id="faq"><div class="container faq-grid"><div><span class="eyebrow">參觀前的問題</span><h2 class="section-title">參觀前，<br>你可能想知道。</h2><p class="section-copy">每個家庭都有不同的考量。<br>把問題帶來，我們一起聊聊。</p></div>${faq()}</div></section>${banner()}`;}
// This is a flat-photo tour. Real 360 media can be supplied separately later.
const tourScenes = [
 {key:'courtyard',name:'戶外廣場',image:'campus',intro:'先從廣場開始，看看孩子每天活動的地方。',spots:[
  {name:'戶外活動空間',x:68,y:72,text:'從照片可以看見校舍圍繞的戶外廣場。開闊的地面與周邊空間，是認識校園環境的第一個視角。',question:'可以詢問戶外活動時段、陪伴方式，以及雨天的替代安排。'},
  {name:'遊戲設施',x:12,y:51,text:'照片左側可看見溜滑梯與遊戲設施。放大照片，看看設施與周邊活動空間的配置。',question:'參觀時可以了解設施適用年齡、使用方式與日常維護。'},
  {name:'校舍與走廊',x:66,y:26,text:'廣場周圍是校舍與走廊。從這個視角，可以先認識室內外空間的關係。',question:'教室配置、孩子移動路線與接送出入口，請向園所確認。'}]},
 {key:'garden',name:'綠色園藝',image:'garden',intro:'靠近一點，看看校園裡的自然細節。',spots:[
  {name:'觀察果實',x:52,y:62,text:'義華校官網的園藝照片記錄了枝葉間的果實。從顏色、形狀與大小開始，看看自然裡的小細節。',question:'可以詢問孩子接觸植物時的活動內容與陪伴方式。'},
  {name:'葉片與枝條',x:29,y:35,text:'綠葉、枝條與果實相互交錯。放大照片，可以看見平常容易忽略的葉片紋理。',question:'參觀時可以了解植物照顧、觀察或種植活動如何安排。'}]},
 {key:'classroom',name:'共創教室',image:'classroom',intro:'走進教室，認識孩子創作與學習的空間。',spots:[
  {name:'桌椅與共作空間',x:63,y:66,text:'教室照片中可以看見成排的桌椅與活動空間。這個視角呈現室內學習環境的配置。',question:'可以向園所了解分組方式，以及如何配合活動調整桌椅。'},
  {name:'材料收納',x:22,y:51,text:'照片左側的櫃架放置了多種材料。透過收納區，可以先認識教室內的素材與空間安排。',question:'參觀時可以詢問材料使用、收拾習慣與生活自理的練習。'},
  {name:'展示與教學區',x:45,y:44,text:'教室前方可見黑板與展示區。搭配完整照片，一起看看不同區域如何分布。',question:'各年齡層的教室與學習安排，請向園所確認。'}]}
];
function scenesFor(key){if(key==='yihua')return tourScenes;const c=campuses[key];return [{key:'exterior',name:'校園外觀',image:c.image,intro:`先從外觀與位置，認識${c.name}。`,spots:[{name:`認識${c.name}`,x:50,y:48,text:`${c.name}位於${c.address}。這張照片取自常春藤機構官網，歡迎放大觀察校園外觀。`,question:'室內環境、參觀動線與接送安排，可直接向園所詢問。'}]}];}
function campusTour(key,homePreview=false){const c=campuses[key],scenes=scenesFor(key);return `<section class="section tour-section" id="${homePreview?'campus-tour':'environment'}" aria-labelledby="tour-heading"><div class="container"><div class="section-heading"><div><span class="eyebrow">校園探索</span><h2 class="section-title" id="tour-heading">先走進校園，<br>再想像孩子的日常。</h2></div><p>點一下照片上的標記，<br>從你最感興趣的地方開始。</p></div><div class="tour-explorer" data-tour-campus="${key}"><div class="tour-toolbar"><div class="tour-location"><span class="tour-location-dot" aria-hidden="true"></span><strong>${c.name}</strong><span>照片探索</span></div><button type="button" class="tour-expand">${icon('arrows-out')}展開檢視</button></div><div class="tour-layout"><div class="tour-visual"><div class="tour-photo-area" role="group" tabindex="0" aria-label="校園照片，放大後可以使用方向鍵移動"><div class="tour-canvas"></div></div><div class="tour-image-tools"><p class="tour-image-help">點選標記，認識這個空間</p><div class="tour-zoom"><button type="button" data-tour-zoom="out" aria-label="縮小照片">${icon('minus')}</button><output class="tour-zoom-value" aria-label="照片縮放比例">100%</output><button type="button" data-tour-zoom="in" aria-label="放大照片">${icon('plus')}</button><button type="button" data-tour-zoom="reset">${icon('arrow-counter-clockwise')}重設</button></div></div><div class="tour-scene-list" role="tablist" aria-label="${c.name}照片場景">${scenes.map((scene,i)=>`<button type="button" class="tour-scene" id="tour-scene-${key}-${i}" role="tab" aria-controls="tour-scene-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-tour-scene="${i}">${img(scene.image,'')}<span>${scene.name}</span></button>`).join('')}</div></div><div class="tour-detail" id="tour-scene-panel" role="tabpanel" aria-labelledby="tour-scene-${key}-0" tabindex="0"></div></div><div class="tour-footnote"><span>${homePreview?'本段為義華校實景；各校環境不同。':'照片取自校區官方網站，實際環境請以到園參觀為準。'}</span><a href="${bookingLink(key)}">預約參觀${c.name}</a></div></div>${homePreview?'<div class="tour-more"><a class="text-link" href="#/home/campuses">繼續認識其他校區</a></div>':''}</div></section>`;}
let disposeTour=()=>{};
function setupCampusTour(){
 const root=document.querySelector('.tour-explorer');if(!root)return;
 const key=root.dataset.tourCampus,scenes=scenesFor(key),area=root.querySelector('.tour-photo-area'),canvas=root.querySelector('.tour-canvas'),detail=root.querySelector('.tour-detail');
 const tabs=[...root.querySelectorAll('[data-tour-scene]')],expand=root.querySelector('.tour-expand');
 let sceneIndex=0,spotIndex=0,zoom=1,panX=0,panY=0,drag=null;const originalParent=root.parentNode;const placeholder=document.createComment('tour-position');root.before(placeholder);
 const fullDialog=document.createElement('dialog');fullDialog.className='tour-dialog';fullDialog.setAttribute('aria-label',campuses[key].name+'照片探索');document.body.append(fullDialog);
 function restore(){if(placeholder.isConnected)placeholder.after(root);root.classList.remove('expanded');expand.innerHTML=icon('arrows-out')+'展開檢視';expand.focus({preventScroll:true});transform();}
 fullDialog.addEventListener('close',restore);
 expand.addEventListener('click',()=>{if(fullDialog.open){fullDialog.close();return;}root.classList.add('expanded');expand.innerHTML=icon('x')+'返回頁面';fullDialog.append(root);fullDialog.showModal();zoom=1;panX=panY=0;transform();});
 function transform(){const maxX=area.clientWidth*(zoom-1)/2,maxY=area.clientHeight*(zoom-1)/2;panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY));canvas.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;root.style.setProperty('--tour-pin-scale',String(1/zoom));area.classList.toggle('zoomed',zoom>1);root.querySelector('.tour-zoom-value').textContent=Math.round(zoom*100)+'%';root.querySelector('[data-tour-zoom="out"]').disabled=zoom===1;root.querySelector('[data-tour-zoom="in"]').disabled=zoom===2;root.querySelector('.tour-image-help').textContent=zoom>1?'拖曳照片，或用方向鍵移動':'點選標記，認識這個空間';}
 function selectSpot(index,focusDetail=false){spotIndex=index;const scene=scenes[sceneIndex],spot=scene.spots[index];canvas.querySelectorAll('.tour-pin').forEach((pin,i)=>pin.setAttribute('aria-pressed',String(index===i)));detail.innerHTML=`<div class="tour-detail-kicker"><span>${scene.name}</span><span>${String(index+1).padStart(2,'0')} / ${String(scene.spots.length).padStart(2,'0')}</span></div><h3 class="tour-spot-title" tabindex="-1">${spot.name}</h3><p class="tour-description">${spot.text}</p><div class="tour-observe"><span>到園時，還可以聊聊</span><p>${spot.question}</p></div><div class="tour-points"><span>這張照片裡</span>${scene.spots.map((s,i)=>`<button type="button" data-tour-spot="${i}" aria-pressed="${i===index}"><span>${String(i+1).padStart(2,'0')}</span>${s.name}<span aria-hidden="true">${i===index?'●':'○'}</span></button>`).join('')}</div><p class="tour-photo-credit">${campuses[key].name} · 官方實景照片</p>`;
  if(focusDetail){detail.querySelector('h3').focus({preventScroll:true});if(matchMedia('(max-width: 760px)').matches)detail.scrollIntoView({block:'nearest',behavior:'instant'});}
 }
 function selectScene(index,focusTab=false){sceneIndex=index;spotIndex=0;const scene=scenes[index];zoom=1;panX=panY=0;tabs.forEach((t,i)=>{t.setAttribute('aria-selected',String(i===index));t.tabIndex=i===index?0:-1;});detail.setAttribute('aria-labelledby',tabs[index].id);canvas.innerHTML=`${img(scene.image,campuses[key].name+' · '+scene.name,'tour-image',true)}${scene.spots.map((s,i)=>`<button type="button" class="tour-pin" style="left:${s.x}%;top:${s.y}%" data-tour-pin="${i}" aria-label="${i+1}：${s.name}" aria-pressed="${i===0}" aria-controls="tour-scene-panel"><span>${i+1}</span><span class="tour-pin-label">${s.name}</span></button>`).join('')}`;const photo=canvas.querySelector('img');photo.draggable=false;const fit=()=>{if(photo.naturalWidth){canvas.style.aspectRatio=photo.naturalWidth+'/'+photo.naturalHeight;transform();}};photo.addEventListener('load',fit,{once:true});if(photo.complete)fit();selectSpot(0);transform();if(focusTab)tabs[index].focus({preventScroll:true});}
 tabs.forEach((t,i)=>{t.addEventListener('click',()=>selectScene(i));t.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();selectScene(next,true);}});});
 canvas.addEventListener('click',e=>{const pin=e.target.closest('[data-tour-pin]');if(pin)selectSpot(Number(pin.dataset.tourPin),true);});
 detail.addEventListener('click',e=>{const button=e.target.closest('[data-tour-spot]');if(button){selectSpot(Number(button.dataset.tourSpot),true);}});
 root.querySelector('.tour-zoom').addEventListener('click',e=>{const b=e.target.closest('[data-tour-zoom]');if(!b)return;const action=b.dataset.tourZoom;zoom=action==='reset'?1:Math.min(2,Math.max(1,zoom+(action==='in'?.5:-.5)));if(zoom===1)panX=panY=0;transform();if(b.disabled)area.focus({preventScroll:true});});
 area.addEventListener('pointerdown',e=>{if(zoom===1||e.target.closest('button'))return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,panX,panY};area.setPointerCapture(e.pointerId);area.classList.add('dragging');});
 area.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;panX=drag.panX+e.clientX-drag.x;panY=drag.panY+e.clientY-drag.y;transform();});
 const endDrag=()=>{drag=null;area.classList.remove('dragging');};area.addEventListener('pointerup',endDrag);area.addEventListener('pointercancel',endDrag);area.addEventListener('lostpointercapture',endDrag);
 area.addEventListener('keydown',e=>{if(e.target!==area||zoom===1)return;const directions={ArrowLeft:[40,0],ArrowRight:[-40,0],ArrowUp:[0,40],ArrowDown:[0,-40]};if(directions[e.key]){e.preventDefault();panX+=directions[e.key][0];panY+=directions[e.key][1];transform();}});
 const resize=new ResizeObserver(transform);resize.observe(area);selectScene(0);
 disposeTour=()=>{resize.disconnect();if(fullDialog.open)fullDialog.close();fullDialog.remove();placeholder.remove();disposeTour=()=>{};};
}

function campusPage(key){const c=campuses[key];return `<div class="container breadcrumb"><a href="#/home">首頁</a> / <a href="#/home/campuses">五校介紹</a> / ${c.name}</div><section class="hero campus-hero">${img(c.image,c.name+'校園外觀','hero-photo',true,true)}<div class="hero-shade"></div><div class="container"><span class="eyebrow">常春藤幼兒園 · 高雄${c.district}</span><h1>${c.name}</h1><p>${c.intro}</p><div class="hero-cta"><a class="button yellow" href="${bookingLink(key)}">預約參觀${c.name}</a></div></div><div class="hero-bottom"><span class="hero-caption">${c.name} · 官方校園照片</span></div></section><nav class="campus-subnav" aria-label="${c.name}頁面段落"><div class="container"><a href="#/${key}/about">認識${c.name}</a><a href="#/${key}/environment">校園環境</a><a href="#/${key}/faq">參觀須知</a><a href="#/${key}/contact">交通與聯絡</a></div></nav>
<section class="section" id="about"><div class="container detail-grid"><div><span class="eyebrow">認識${c.name}</span><h2 class="section-title">${c.intro}</h2><p class="section-copy">${c.description}</p><p class="section-copy">不急著做決定，先從一次親自走訪開始。帶著你想了解的事情，看看這裡是否適合孩子。</p></div><div class="contact-panel"><h3>來認識${c.name}</h3><dl><div><dt>${icon('map-pin')}所在地</dt><dd>${c.address}</dd></div><div><dt>${icon('phone')}參觀專線</dt><dd><a href="tel:${c.phone}">${c.phone}</a></dd></div><div><dt>${icon('clock')}到園參觀</dt><dd>請事先聯絡園所確認接待時間。</dd></div></dl><a class="text-link" href="${mapURL(c)}" ${external}>查看地圖與路線 ${arrow}</a></div></div></section>
${campusTour(key)}
<section class="section" id="faq"><div class="container faq-grid"><div><span class="eyebrow">參觀須知</span><h2 class="section-title">讓第一次參觀，<br>更安心一點。</h2><p class="section-copy">參觀時間、課程與入學安排，<br>請直接向${c.name}確認。</p></div>${faq(key)}</div></section>
<section class="section campuses" id="contact"><div class="container detail-grid"><div class="contact-location"><span class="eyebrow">交通與聯絡</span><h2 class="section-title">我們在這裡，等你來。</h2><a class="phone-link" href="tel:${c.phone}">${icon('phone')}${c.phone}</a><p>${c.address}</p><div><a class="button primary" href="${bookingLink(key)}">預約${c.name}</a></div></div><div class="contact-panel"><h3>規劃到園路線</h3><p class="section-copy">參觀前可先查看校區位置，評估從家裡出發的接送動線。停車與出入口安排，請事先向園所詢問。</p><a class="text-link" href="${mapURL(c)}" ${external}>開啟 Google 地圖 ${arrow}</a></div></div></section>${banner(key)}`;}
function visitPage(key){return `<section class="visit-page"><div class="container"><div class="breadcrumb"><a href="#/home">首頁</a> / 預約校園參觀</div><div class="visit-layout"><div class="visit-intro"><span class="eyebrow">預約校園參觀</span><h1>一起認識，<br>孩子未來的日常。</h1><p>選一所你想了解的校園，<br>留下方便聯絡的方式。</p><p class="demo-note">這是官網互動提案，請使用測試資料。<br>資料不會送出或儲存，也不會建立預約。<br>實際參觀請直接致電各校。</p></div><div><ol class="stepper" aria-label="預約步驟"><li id="step-one" aria-current="step"><span>1</span>選擇校區</li><li id="step-two"><span>2</span>填寫聯絡資料</li></ol><div class="form-panel"><section id="choose-campus"><h2>想先認識哪所校園？</h2><p>依照你的生活圈與接送路線選擇。</p><form id="campus-form"><fieldset class="campus-options"><legend class="sr-only">選擇想參觀的校區（必填）</legend>${Object.entries(campuses).map(([id,c])=>`<label class="campus-option"><input type="radio" name="campus" value="${id}" ${key===id?'checked':''} required><span><strong>${c.name}</strong><small>${c.address}</small></span><span class="district">${c.district}</span></label>`).join('')}</fieldset><div class="form-buttons"><button class="button primary" type="submit">下一步：填寫資料${icon('arrow-right')}</button></div></form></section>
<section id="contact-step" hidden><h2 tabindex="-1" id="contact-title">怎麼稱呼你？</h2><div class="selected-school"><span id="selected-school-name"></span><button id="change-campus" type="button">更換校區</button></div><form id="booking-form"><div class="field-grid"><div class="field"><label for="parent-name">家長稱呼<span class="required">必填</span></label><input id="parent-name" name="parentName" autocomplete="off" maxlength="40" required placeholder="例如：陳媽媽"></div><div class="field"><label for="parent-phone">手機號碼<span class="required">必填</span></label><input id="parent-phone" name="phone" autocomplete="off" type="tel" inputmode="tel" maxlength="16" required pattern="09[0-9]{8}" title="09 開頭的 10 碼手機號碼" placeholder="09xxxxxxxx" aria-describedby="phone-hint"><small id="phone-hint">請填寫 09 開頭的 10 碼手機號碼。</small></div><div class="field"><label for="child-age">孩子年齡</label><select id="child-age" name="age"><option>尚未確定</option><option>2 歲以下</option><option>2–3 歲</option><option>3–4 歲</option><option>4–5 歲</option><option>5–6 歲</option></select></div><div class="field"><label for="contact-time">方便聯絡的時段</label><select id="contact-time" name="time"><option>時間彈性</option><option>平日上午</option><option>平日下午</option><option>其他，另行確認</option></select></div><div class="field full"><label for="questions">有沒有想先了解的事？<span class="required">選填</span></label><textarea id="questions" name="questions" maxlength="500" placeholder="例如：課程安排、生活照顧、入學準備……"></textarea></div></div><label class="consent"><input type="checkbox" required id="demo-consent"><span>我了解這是操作示範，資料不會傳送給學校，不代表預約成立。</span></label><p class="form-error" id="form-error" role="alert"></p><div class="form-buttons"><button type="button" class="button outline" id="back-step">${icon('arrow-left')}上一步</button><button type="submit" class="button primary">預覽填寫結果${icon('arrow-right')}</button></div></form></section><section id="booking-result" hidden tabindex="-1"><div class="result-mark" aria-hidden="true">${icon('check')}</div><span class="eyebrow">示範結果</span><h2>示範完成，尚未送出預約。</h2><p>以下為本次填寫內容。若要實際安排參觀，請撥打所選校區的電話；離開此頁後將清除輸入資料。</p><dl class="result-list" id="result-list"></dl><div class="form-buttons"><button class="button outline" type="button" id="edit-result">修改內容</button><a class="button primary" id="call-campus">${icon('phone')}致電園所</a></div><a class="text-link" style="margin-top:24px" href="#/home">回到首頁</a></section></div></div></div></div></section>`;}
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','開啟導覽選單');}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'關閉導覽選單':'開啟導覽選單');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
window.matchMedia('(min-width: 761px)').addEventListener('change',closeMenu);
document.querySelector('#footer-campuses').innerHTML=Object.entries(campuses).map(([key,c])=>`<a href="#/${key}">${c.name}</a>`).join('');
function setupBooking(key){
 let selected=campuses[key]?key:'';
 const choose=document.querySelector('#choose-campus'),contact=document.querySelector('#contact-step'),result=document.querySelector('#booking-result');
 const form=document.querySelector('#booking-form');
 function step(n,focus=true){choose.hidden=n!==1;contact.hidden=n!==2;result.hidden=n!==3;document.querySelector('#step-one').toggleAttribute('aria-current',n===1);document.querySelector('#step-two').toggleAttribute('aria-current',n===2);if(n<3)document.querySelector(n===1?'#step-one':'#step-two').setAttribute('aria-current','step');if(n===2){document.querySelector('#selected-school-name').textContent=`${campuses[selected].name} · ${campuses[selected].district}`;}if(focus){const target=n===1?choose.querySelector('input:checked')||choose.querySelector('input'):n===2?document.querySelector('#contact-title'):result;target.focus({preventScroll:true});const panel=document.querySelector('.form-panel');if(panel.getBoundingClientRect().top<90||window.innerWidth<761)panel.scrollIntoView({block:'start',behavior:'instant'});}}
 document.querySelector('#campus-form').addEventListener('submit',e=>{e.preventDefault();selected=new FormData(e.currentTarget).get('campus');if(campuses[selected])step(2);});
 document.querySelector('#change-campus').addEventListener('click',()=>step(1));document.querySelector('#back-step').addEventListener('click',()=>step(1));document.querySelector('#edit-result').addEventListener('click',()=>step(2));
 const name=document.querySelector('#parent-name'),phone=document.querySelector('#parent-phone');
 name.addEventListener('input',()=>name.setCustomValidity(''));
 name.addEventListener('blur',()=>{name.value=name.value.trim();name.setCustomValidity(name.value?'':'請填寫家長稱呼。');});
 phone.addEventListener('input',()=>{phone.value=phone.value.replace(/[\s-]/g,'');});
 form.addEventListener('submit',e=>{e.preventDefault();name.value=name.value.trim();name.setCustomValidity(name.value?'':'請填寫家長稱呼。');if(!form.reportValidity())return;const c=campuses[selected];const data=new FormData(form);const values=[['想參觀的校區',c.name],['家長稱呼',data.get('parentName')],['手機號碼',data.get('phone')],['孩子年齡',data.get('age')],['方便聯絡時段',data.get('time')],['想了解的事',data.get('questions').trim()||'未填寫']];const dl=document.querySelector('#result-list');dl.replaceChildren();for(const [title,value] of values){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=title;dd.textContent=value;div.append(dt,dd);dl.append(div);}document.querySelector('#call-campus').href='tel:'+c.phone;step(3);});
 if(selected)step(2,false);
}
function setupVideo(){if(!HERO_VIDEO_SRC)return;const video=document.querySelector('#hero-video'),controls=document.querySelector('#video-controls'),caption=document.querySelector('#media-caption'),play=document.querySelector('#video-play'),sound=document.querySelector('#video-sound');video.src=HERO_VIDEO_SRC;video.preload='metadata';video.hidden=false;controls.hidden=false;caption.textContent='常春藤校園影片';const sync=()=>play.innerHTML=video.paused?icon('play')+'播放影片':icon('pause')+'暫停影片';video.addEventListener('play',sync);video.addEventListener('pause',sync);video.addEventListener('error',()=>{video.hidden=true;controls.hidden=true;caption.textContent='影片暫時無法播放 · 義華校生活影像';});play.addEventListener('click',()=>{if(video.paused)video.play().catch(()=>{caption.textContent='無法播放影片，請稍後再試';});else video.pause();});sound.addEventListener('click',()=>{video.muted=!video.muted;sound.innerHTML=video.muted?icon('speaker-high')+'開啟聲音':icon('speaker-slash')+'關閉聲音';sound.setAttribute('aria-pressed',String(!video.muted));});if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&!navigator.connection?.saveData)video.play().catch(sync);const visibility=()=>{if(document.hidden)video.pause();};document.addEventListener('visibilitychange',visibility);disposeMedia=()=>{video.pause();video.removeAttribute('src');video.load();document.removeEventListener('visibilitychange',visibility);};}
const dialog=document.querySelector('#photo-dialog');document.querySelector('#photo-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{lastPhotoTrigger?.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
main.addEventListener('click',e=>{const trigger=e.target.closest('[data-photo]');if(!trigger)return;lastPhotoTrigger=trigger;document.querySelector('#photo-title').textContent=trigger.dataset.title;document.querySelector('#photo-image').src='assets/'+trigger.dataset.photo+'.webp';document.querySelector('#photo-image').alt=trigger.dataset.title;dialog.showModal();});
function render(){const version=++routeVersion;const parts=location.hash.replace(/^#\/?/,'').split('/');let page=parts[0]||'home';if(!campuses[page]&&page!=='visit')page='home';const school=page==='visit'&&campuses[parts[1]]?parts[1]:'';const id=page==='visit'?'':parts[1]||'';const pageKey=page+(page==='visit'?'/'+school:'');closeMenu();if(currentPage!==pageKey){disposeTour();disposeMedia();disposeMedia=()=>{};if(dialog.open)dialog.close();currentPage=pageKey;main.innerHTML=page==='home'?home():page==='visit'?visitPage(school):campusPage(page);document.title=page==='home'?'常春藤幼兒園｜讓每一份好奇，慢慢長大':page==='visit'?'預約校園參觀｜常春藤幼兒園':campuses[page].name+'｜常春藤幼兒園';document.querySelector('.header-book').href=bookingLink(campuses[page]?page:'');if(page==='visit')setupBooking(school);if(page==='home'){setupVideo();setupDayExperience();}setupCampusTour();}document.querySelectorAll('.nav-inner a').forEach(a=>{if(a.getAttribute('href')===location.hash)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});requestAnimationFrame(()=>{if(version!==routeVersion)return;const target=id?document.getElementById(id):null;if(target){target.scrollIntoView({block:'start',behavior:'instant'});target.setAttribute('tabindex','-1');target.focus({preventScroll:true});}else{window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}});}
window.addEventListener('hashchange',render);document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#/"]');if(a&&a.getAttribute('href')===location.hash){e.preventDefault();render();}});render();
