from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ed117ce6188'
down_revision: Union[str, None] = '17e4529c92c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_configs',
    sa.Column('campus_key', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.Enum('INQUIRY', 'SLOTS', 'LINE', 'PHONE', 'EXTERNAL', 'PAUSED', name='booking_mode'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('line_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('campus_key')
    )
    op.create_table('visit_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('age', sa.String(length=32), nullable=True),
    sa.Column('preferred_time', sa.String(length=32), nullable=True),
    sa.Column('questions', sa.String(length=1000), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_key', 'idempotency_key', name='uq_visit_request_idempotency')
    )
    op.create_index(op.f('ix_visit_requests_campus_key'), 'visit_requests', ['campus_key'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visit_request_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visit_request_id'], ['visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_messages_visit_request_id'), 'outbox_messages', ['visit_request_id'], unique=False)
    op.create_table('visit_request_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visit_request_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['visit_request_id'], ['visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_request_events_visit_request_id'), 'visit_request_events', ['visit_request_id'], unique=False)
    op.create_foreign_key(None, 'content_items', 'content_revisions', ['current_published_revision_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_index(op.f('ix_visit_request_events_visit_request_id'), table_name='visit_request_events')
    op.drop_table('visit_request_events')
    op.drop_index(op.f('ix_outbox_messages_visit_request_id'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_visit_requests_campus_key'), table_name='visit_requests')
    op.drop_table('visit_requests')
    op.drop_table('booking_configs')
    # ### end Alembic commands ###
