from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '801fb8466a52'
down_revision: Union[str, None] = '09d6373bbeec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.Enum('IMAGE', 'VIDEO', name='media_kind'), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'READY', 'FAILED', name='media_status'), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('source_attribution', sa.String(length=255), nullable=True),
    sa.Column('crop_focus_x', sa.Float(), nullable=True),
    sa.Column('crop_focus_y', sa.Float(), nullable=True),
    sa.Column('processing_error', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replaces_media_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaces_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('media_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=True),
    sa.Column('content_item_id', sa.String(length=128), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_usages_media_id'), 'media_usages', ['media_id'], unique=False)
    op.create_table('media_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('THUMBNAIL', 'POSTER', name='media_variant_kind'), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_media_variants_media_id'), 'media_variants', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_variants_media_id'), table_name='media_variants')
    op.drop_table('media_variants')
    op.drop_index(op.f('ix_media_usages_media_id'), table_name='media_usages')
    op.drop_table('media_usages')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
