from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bdab28195e09'
down_revision: Union[str, None] = 'bb68559bda1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_messages', sa.Column('status', sa.String(length=16), nullable=False))
    op.add_column('outbox_messages', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('outbox_messages', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('outbox_messages', sa.Column('error_code', sa.String(length=64), nullable=True))
    op.add_column('outbox_messages', sa.Column('leased_by', sa.String(length=64), nullable=True))
    op.add_column('outbox_messages', sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_messages', 'leased_until')
    op.drop_column('outbox_messages', 'leased_by')
    op.drop_column('outbox_messages', 'error_code')
    op.drop_column('outbox_messages', 'next_attempt_at')
    op.drop_column('outbox_messages', 'attempts')
    op.drop_column('outbox_messages', 'status')
    # ### end Alembic commands ###
