from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17e4529c92c4'
down_revision: Union[str, None] = '801fb8466a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=True),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('current_published_revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_published_revision_id'], ['content_revisions.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'campus_key', name='uq_content_item_kind_campus')
    )
    op.create_table('site_releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_revisions_content_item_id'), 'content_revisions', ['content_item_id'], unique=False)
    op.create_table('site_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_release_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['current_release_id'], ['site_releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_release_entries',
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['site_releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['content_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('release_id', 'content_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_release_entries')
    op.drop_table('site_state')
    op.drop_index(op.f('ix_content_revisions_content_item_id'), table_name='content_revisions')
    op.drop_table('content_revisions')
    op.drop_table('site_releases')
    op.drop_table('content_items')
    # ### end Alembic commands ###
