from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce3082c9bf69'
down_revision: Union[str, None] = 'f5583e921dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('share_image', sa.String(length=255), nullable=True),
    sa.Column('noindex', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_version', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('CTA_CLICK_LINE', 'CTA_CLICK_PHONE', 'CTA_CLICK_EXTERNAL', 'REQUEST_CREATED', 'VISIT_CONFIRMED', 'VISIT_COMPLETED', name='analytics_event_type'), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_campus_key'), 'analytics_events', ['campus_key'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('visit_requests', sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_requests', 'anonymized_at')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_analytics_events_campus_key'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_table('site_settings')
    # ### end Alembic commands ###
