from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f5583e921dd6'
down_revision: Union[str, None] = 'bdab28195e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_inbox_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campus_key', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_key'], ['campuses.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_inbox_items_campus_key'), 'notification_inbox_items', ['campus_key'], unique=False)
    op.create_table('parent_access_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visit_request_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visit_request_id'], ['visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_parent_access_tokens_visit_request_id'), 'parent_access_tokens', ['visit_request_id'], unique=False)
    op.create_table('parent_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('visit_request_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visit_request_id'], ['visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_sessions_visit_request_id'), 'parent_sessions', ['visit_request_id'], unique=False)
    op.create_table('reschedule_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visit_request_id', sa.Uuid(), nullable=False),
    sa.Column('requested_slot_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_slot_id'], ['visit_slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_request_id'], ['visit_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reschedule_requests_visit_request_id'), 'reschedule_requests', ['visit_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reschedule_requests_visit_request_id'), table_name='reschedule_requests')
    op.drop_table('reschedule_requests')
    op.drop_index(op.f('ix_parent_sessions_visit_request_id'), table_name='parent_sessions')
    op.drop_table('parent_sessions')
    op.drop_index(op.f('ix_parent_access_tokens_visit_request_id'), table_name='parent_access_tokens')
    op.drop_table('parent_access_tokens')
    op.drop_index(op.f('ix_notification_inbox_items_campus_key'), table_name='notification_inbox_items')
    op.drop_table('notification_inbox_items')
    # ### end Alembic commands ###
