'use strict';
const moments=[
 {key:'hello',label:'早安入園',short:'入園',period:'一天的開始',title:'一聲早安，開啟今天的小冒險。',hint:'從熟悉的陪伴，開始安心的一天。',story:'和家人說聲再見，走進熟悉的校園。從整理小書包開始，一點一點，找到自己的步調。',image:'campus',caption:'義華校校園照片 · 入園情境示意',question:'孩子第一次上學，如何陪伴適應？',answer:'參觀時可以詢問入園陪伴、親師聯繫與事前準備，了解園所如何陪孩子熟悉新環境。'},
 {key:'discover',label:'好奇探索',short:'探索',period:'上午的發現',title:'原來，世界有這麼多為什麼。',hint:'看一看、試一試，讓好奇心帶路。',story:'摸一摸、看一看，和同伴一起試試看。每一個「為什麼」，都是認識世界的開始。',image:'learning',caption:'義華校 · 孩子的探索片刻',question:'孩子平常會接觸哪些學習活動？',answer:'參觀時可以看看教具與素材，聊聊探索活動如何依孩子的年齡、興趣與班級需要調整。'},
 {key:'lunch',label:'一起用餐',short:'用餐',period:'午間的小事',title:'「我自己來！」是今天的小進步。',hint:'成長，也藏在生活的小事情裡。',story:'洗洗手、準備用餐，練習把自己的小事做好。在熟悉的日常裡，一點一點學會照顧自己。',image:'classroom',caption:'義華校教室空間參考 · 用餐實拍待補',question:'餐點、飲食需求與自理練習怎麼安排？',answer:'可以向園所詢問餐點安排、過敏或特殊飲食的溝通方式，以及老師如何協助孩子用餐。'},
 {key:'rest',label:'安靜片刻',short:'休息',period:'慢下來的午後',title:'小小的世界，也需要休息一下。',hint:'慢一點，也是在好好長大。',story:'把腳步放慢，讓身體好好休息。安靜一下、充飽精神，再迎接下午的新發現。',image:'classroom',caption:'義華校教室空間參考 · 午休實拍待補',question:'孩子睡不著，或有不同的休息需求呢？',answer:'參觀時可以詢問休息空間、不習慣午休時的陪伴方式，以及園所如何和家長一起了解孩子的需要。'},
 {key:'outside',label:'午後玩耍',short:'玩耍',period:'午後的冒險',title:'和朋友一起，把今天玩得好大。',hint:'一小片自然，也能裝下很多發現。',story:'看看植物、動動身體，發現身邊的新鮮事。和同伴一起玩的時候，也在練習分享與表達。',image:'hero',caption:'義華校生活照片 · 戶外玩耍情境',question:'戶外活動與天氣變化如何安排？',answer:'可以詢問戶外活動空間、陪伴方式，以及下雨或天氣炎熱時，園所如何調整當天安排。'},
 {key:'home',label:'帶故事回家',short:'回家',period:'把今天帶回家',title:'今天的好多事，想第一個告訴你。',hint:'把新發現，帶回最熟悉的懷抱。',story:'帶上書包，也帶上今天的新發現。和家人分享一件開心的小事，讓校園裡的故事繼續走進生活。',image:'hero-campus-still',caption:'常春藤校園影片畫面 · 離園情境示意',question:'接送與家長聯繫，有哪些需要先知道？',answer:'可以詢問接送流程、家長與老師的聯繫方式，以及如何了解孩子在校的生活情況。'}
];
const el=document.querySelector('#day-content');const direction=new URLSearchParams(location.search).get('direction')||'a';
const arrow=(left=false)=>`<svg class="icon" aria-hidden="true" focusable="false" viewBox="0 0 24 24"><path d="${left?'M19 12H5m6-6-6 6 6 6':'M5 12h14m-6-6 6 6-6 6'}"/></svg>`;
const num=i=>String(i+1).padStart(2,'0');
const photo=m=>`<figure class="picture"><img src="../../assets/${m.image}.webp" alt="${m.caption}" width="1000" height="600"><figcaption class="caption">${m.caption}</figcaption></figure>`;
const question=m=>`<details class="parent-question"><summary><span><small>家長也想知道</small>${m.question}</span></summary><p>${m.answer}</p></details>`;
const heading=description=>`<header class="section-heading"><div><span class="eyebrow">孩子的一天</span><h1>跟著孩子，過一天。</h1></div><p>${description}</p></header>`;
const foot=()=>`<footer class="section-foot"><p>每個片刻，都是成長的一部分。<br>以校園影像呈現日常情境，各校與各班作息請向園所確認。</p><a class="text-link" href="../../#/home/campuses" target="_top">想親自看看？認識五所校園</a></footer>`;
const behavior=()=>matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth';
function chapters(){
 el.innerHTML=`<section class="surface chapters"><div class="wrap">${heading('從一聲早安，到帶著故事回家。<br>看看孩子如何在日常裡，一點一點長大。')}<div class="chapter-layout"><div class="chapter-nav" role="tablist" aria-label="選擇一天中的片刻" aria-orientation="vertical">${moments.map((m,i)=>`<button class="chapter-tab" id="chapter-${m.key}" role="tab" aria-selected="false" aria-controls="chapter-panel" tabindex="-1" data-index="${i}"><span class="chapter-number">${num(i)}</span><span class="chapter-label">${m.label}</span>${arrow()}<span class="chapter-hint">${m.hint}</span></button>`).join('')}</div><div class="chapter-story" id="chapter-panel" role="tabpanel" tabindex="0"></div></div>${foot()}<p class="sr-only" id="chapter-status" aria-live="polite"></p></div></section>`;
 const tabs=[...el.querySelectorAll('.chapter-tab')],panel=el.querySelector('#chapter-panel');let current=1;
 const mq=matchMedia('(max-width:700px)');const orientation=()=>el.querySelector('.chapter-nav').setAttribute('aria-orientation',mq.matches?'horizontal':'vertical');orientation();mq.addEventListener('change',orientation);
 function show(i,announce=true){current=i;const m=moments[i];tabs.forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;});panel.setAttribute('aria-labelledby',tabs[i].id);panel.innerHTML=`${photo(m)}<h2>${m.title}</h2><p class="story">${m.story}</p>${question(m)}<div class="chapter-end"><button class="chapter-next">${i===5?'回到第一個片刻':`<span>下一個片刻</span> ${moments[i+1].label}`}${arrow()}</button></div>`;panel.querySelector('.chapter-next').addEventListener('click',()=>{show((current+1)%moments.length);panel.focus({preventScroll:true});if(mq.matches)panel.scrollIntoView({block:'start',behavior:behavior()});});if(announce)el.querySelector('#chapter-status').textContent=`第 ${i+1} 個片刻：${m.label}`;}
 tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>show(i));tab.addEventListener('keydown',e=>{let n;if(e.key==='Home')n=0;if(e.key==='End')n=5;if(e.key==='ArrowDown'||e.key==='ArrowRight')n=(i+1)%6;if(e.key==='ArrowUp'||e.key==='ArrowLeft')n=(i+5)%6;if(n!==undefined){e.preventDefault();show(n);tabs[n].focus();}});});show(1,false);
}
function album(){
 el.innerHTML=`<section class="surface album"><div class="wrap"><header class="section-heading"><div><span class="eyebrow">孩子的一天</span><h1>小小日常，大大發現。</h1><p>翻一翻生活相簿，看看孩子眼中的世界。</p></div><div class="album-controls"><button class="round" id="album-prev" aria-label="上一個片刻">${arrow(true)}</button><button class="round" id="album-next" aria-label="下一個片刻">${arrow()}</button></div></header></div><div class="album-rail" role="region" aria-roledescription="輪播相簿" aria-label="六個生活片刻，可左右捲動" tabindex="0">${moments.map((m,i)=>`<article class="album-slide" id="album-${m.key}" role="group" aria-roledescription="片刻" aria-label="${i+1} / 6 ${m.label}">${photo(m)}<div class="album-copy"><span class="album-label">${num(i)} / ${m.label}</span><h2>${m.title}</h2><p class="story">${m.story}</p>${question(m)}</div></article>`).join('')}</div><div class="wrap"><nav class="album-nav" aria-label="跳到生活片刻">${moments.map((m,i)=>`<button data-index="${i}" aria-controls="album-${m.key}" aria-current="false">${num(i)} ${m.label}</button>`).join('')}</nav><footer class="section-foot"><span class="album-position" aria-live="polite" id="album-position"></span><a class="text-link" href="../../#/home/campuses" target="_top">認識五所校園</a><p>校園日常情境示意，各校與各班作息請向園所確認。</p></footer></div></section>`;
 const rail=el.querySelector('.album-rail'),slides=[...el.querySelectorAll('.album-slide')],nav=[...el.querySelectorAll('.album-nav button')],prev=el.querySelector('#album-prev'),next=el.querySelector('#album-next');let current=1,raf=0;
 function mark(i){current=i;nav.forEach((b,j)=>b.setAttribute('aria-current',String(i===j)));prev.disabled=i===0;next.disabled=i===5;el.querySelector('#album-position').textContent=`${num(i)} / 06　${moments[i].label}`;}
 function go(i,smooth=true){i=Math.max(0,Math.min(5,i));mark(i);const item=slides[i];const padding=parseFloat(getComputedStyle(rail).paddingLeft);rail.scrollTo({left:item.offsetLeft-rail.offsetLeft-padding,behavior:smooth?behavior():'instant'});}
 function sync(){raf=0;const start=rail.getBoundingClientRect().left+parseFloat(getComputedStyle(rail).paddingLeft);let best=0,distance=Infinity;slides.forEach((s,i)=>{const d=Math.abs(s.getBoundingClientRect().left-start);if(d<distance){distance=d;best=i;}});if(best!==current)mark(best);}
 rail.addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(sync);},{passive:true});if('onscrollsnapchange' in rail)rail.addEventListener('scrollsnapchange',e=>{const i=slides.indexOf(e.snapTargetInline);if(i>=0)mark(i);});
 rail.addEventListener('keydown',e=>{if(e.target!==rail)return;let n;if(e.key==='ArrowLeft')n=current-1;if(e.key==='ArrowRight')n=current+1;if(e.key==='Home')n=0;if(e.key==='End')n=5;if(n!==undefined){e.preventDefault();go(n);}});
 nav.forEach((b,i)=>b.addEventListener('click',()=>go(i)));prev.addEventListener('click',()=>go(current-1));next.addEventListener('click',()=>go(current+1));new ResizeObserver(()=>go(current,false)).observe(rail);go(1,false);
}
function journey(){
 el.innerHTML=`<section class="surface journey wrap">${heading('孩子的一天，藏著好多值得記住的小事。<br>跟著這些片刻，一起走進校園生活。')}<div class="journey-layout"><nav class="journey-nav" aria-label="一天的旅程"><p>一天的六個片刻</p>${moments.map((m,i)=>`<a href="#journey-${m.key}" ${i===0?'aria-current="location"':''}>${num(i)} ${m.short}</a>`).join('')}</nav><div class="journey-chapters">${moments.map((m,i)=>`<article class="journey-chapter" id="journey-${m.key}" tabindex="-1"><div class="journey-copy"><span class="eyebrow">${num(i)} / ${m.label}</span><h2>${m.title}</h2><p class="story">${m.story}</p>${question(m)}</div>${photo(m)}</article>`).join('')}<footer class="section-foot"><div><span class="eyebrow">每一種步調，都值得被陪伴</span><h2>下一個故事，<br>一起走進校園看看。</h2><p>校園日常情境示意，各校與各班作息請向園所確認。</p></div><a class="text-link" href="../../#/home/campuses" target="_top">認識五所校園</a></footer></div></div></section>`;
 const chapters=[...el.querySelectorAll('.journey-chapter')],links=[...el.querySelectorAll('.journey-nav a')];let raf=0;
 const mark=i=>links.forEach((link,j)=>{if(i===j)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});
 function sync(){raf=0;let i=0;chapters.forEach((c,j)=>{if(c.getBoundingClientRect().top<innerHeight*.4)i=j;});mark(i);}
 addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(sync);},{passive:true});links.forEach((link,i)=>link.addEventListener('click',e=>{e.preventDefault();chapters[i].scrollIntoView({behavior:behavior(),block:'start'});chapters[i].focus({preventScroll:true});history.replaceState(null,'',`?direction=c#journey-${moments[i].key}`);mark(i);}));
}
if(direction==='b')album();else if(direction==='c')journey();else chapters();
